cmake_minimum_required(VERSION 3.16)
project(data_injector)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(tf2_ros REQUIRED)
add_executable(injector src/injector.cpp)
ament_target_dependencies(injector rclcpp sensor_msgs geometry_msgs tf2_ros)
install(TARGETS injector DESTINATION lib/${PROJECT_NAME})
ament_package()
